/**
 * currencyapi
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AvailableCurrency', 'model/AvailableCurrencyResponse', 'model/ConvertedCurrencyResult', 'model/ExchangeRateResult', 'api/CurrencyExchangeApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AvailableCurrency'), require('./model/AvailableCurrencyResponse'), require('./model/ConvertedCurrencyResult'), require('./model/ExchangeRateResult'), require('./api/CurrencyExchangeApi'));
  }
}(function(ApiClient, AvailableCurrency, AvailableCurrencyResponse, ConvertedCurrencyResult, ExchangeRateResult, CurrencyExchangeApi) {
  'use strict';

  /**
   * The_currency_APIs_help_you_retrieve_exchange_rates_and_convert_prices_between_currencies_easily_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var CloudmersiveCurrencyApiClient = require('index'); // See note below*.
   * var xxxSvc = new CloudmersiveCurrencyApiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new CloudmersiveCurrencyApiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new CloudmersiveCurrencyApiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new CloudmersiveCurrencyApiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.2.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AvailableCurrency model constructor.
     * @property {module:model/AvailableCurrency}
     */
    AvailableCurrency: AvailableCurrency,
    /**
     * The AvailableCurrencyResponse model constructor.
     * @property {module:model/AvailableCurrencyResponse}
     */
    AvailableCurrencyResponse: AvailableCurrencyResponse,
    /**
     * The ConvertedCurrencyResult model constructor.
     * @property {module:model/ConvertedCurrencyResult}
     */
    ConvertedCurrencyResult: ConvertedCurrencyResult,
    /**
     * The ExchangeRateResult model constructor.
     * @property {module:model/ExchangeRateResult}
     */
    ExchangeRateResult: ExchangeRateResult,
    /**
     * The CurrencyExchangeApi service constructor.
     * @property {module:api/CurrencyExchangeApi}
     */
    CurrencyExchangeApi: CurrencyExchangeApi
  };

  return exports;
}));
