/**
 * currencyapi
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveCurrencyApiClient);
  }
}(this, function(expect, CloudmersiveCurrencyApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveCurrencyApiClient.AvailableCurrencyResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AvailableCurrencyResponse', function() {
    it('should create an instance of AvailableCurrencyResponse', function() {
      // uncomment below and update the code to test AvailableCurrencyResponse
      //var instane = new CloudmersiveCurrencyApiClient.AvailableCurrencyResponse();
      //expect(instance).to.be.a(CloudmersiveCurrencyApiClient.AvailableCurrencyResponse);
    });

    it('should have the property currencies (base name: "Currencies")', function() {
      // uncomment below and update the code to test the property currencies
      //var instane = new CloudmersiveCurrencyApiClient.AvailableCurrencyResponse();
      //expect(instance).to.be();
    });

  });

}));
