/**
 * currencyapi
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveCurrencyApiClient);
  }
}(this, function(expect, CloudmersiveCurrencyApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveCurrencyApiClient.ConvertedCurrencyResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConvertedCurrencyResult', function() {
    it('should create an instance of ConvertedCurrencyResult', function() {
      // uncomment below and update the code to test ConvertedCurrencyResult
      //var instane = new CloudmersiveCurrencyApiClient.ConvertedCurrencyResult();
      //expect(instance).to.be.a(CloudmersiveCurrencyApiClient.ConvertedCurrencyResult);
    });

    it('should have the property convertedPrice (base name: "ConvertedPrice")', function() {
      // uncomment below and update the code to test the property convertedPrice
      //var instane = new CloudmersiveCurrencyApiClient.ConvertedCurrencyResult();
      //expect(instance).to.be();
    });

    it('should have the property iSOCurrencyCode (base name: "ISOCurrencyCode")', function() {
      // uncomment below and update the code to test the property iSOCurrencyCode
      //var instane = new CloudmersiveCurrencyApiClient.ConvertedCurrencyResult();
      //expect(instance).to.be();
    });

    it('should have the property currencySymbol (base name: "CurrencySymbol")', function() {
      // uncomment below and update the code to test the property currencySymbol
      //var instane = new CloudmersiveCurrencyApiClient.ConvertedCurrencyResult();
      //expect(instance).to.be();
    });

    it('should have the property formattedPriceAsString (base name: "FormattedPriceAsString")', function() {
      // uncomment below and update the code to test the property formattedPriceAsString
      //var instane = new CloudmersiveCurrencyApiClient.ConvertedCurrencyResult();
      //expect(instance).to.be();
    });

  });

}));
