/**
 * currencyapi
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveCurrencyApiClient) {
      root.CloudmersiveCurrencyApiClient = {};
    }
    root.CloudmersiveCurrencyApiClient.AvailableCurrency = factory(root.CloudmersiveCurrencyApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AvailableCurrency model module.
   * @module model/AvailableCurrency
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>AvailableCurrency</code>.
   * Details of a specific currency
   * @alias module:model/AvailableCurrency
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>AvailableCurrency</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AvailableCurrency} obj Optional instance to populate.
   * @return {module:model/AvailableCurrency} The populated <code>AvailableCurrency</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ISOCurrencyCode')) {
        obj['ISOCurrencyCode'] = ApiClient.convertToType(data['ISOCurrencyCode'], 'String');
      }
      if (data.hasOwnProperty('CurrencySymbol')) {
        obj['CurrencySymbol'] = ApiClient.convertToType(data['CurrencySymbol'], 'String');
      }
      if (data.hasOwnProperty('CurrencyEnglishName')) {
        obj['CurrencyEnglishName'] = ApiClient.convertToType(data['CurrencyEnglishName'], 'String');
      }
      if (data.hasOwnProperty('CountryName')) {
        obj['CountryName'] = ApiClient.convertToType(data['CountryName'], 'String');
      }
      if (data.hasOwnProperty('CountryThreeLetterCode')) {
        obj['CountryThreeLetterCode'] = ApiClient.convertToType(data['CountryThreeLetterCode'], 'String');
      }
      if (data.hasOwnProperty('CountryISOTwoLetterCode')) {
        obj['CountryISOTwoLetterCode'] = ApiClient.convertToType(data['CountryISOTwoLetterCode'], 'String');
      }
      if (data.hasOwnProperty('IsEuropeanUnionMember')) {
        obj['IsEuropeanUnionMember'] = ApiClient.convertToType(data['IsEuropeanUnionMember'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * ISO 4217 currency three-letter code associated with the country
   * @member {String} ISOCurrencyCode
   */
  exports.prototype['ISOCurrencyCode'] = undefined;
  /**
   * Symbol associated with the currency
   * @member {String} CurrencySymbol
   */
  exports.prototype['CurrencySymbol'] = undefined;
  /**
   * Full name of the currency
   * @member {String} CurrencyEnglishName
   */
  exports.prototype['CurrencyEnglishName'] = undefined;
  /**
   * Name of the country
   * @member {String} CountryName
   */
  exports.prototype['CountryName'] = undefined;
  /**
   * Three-letter ISO 3166-1 country code
   * @member {String} CountryThreeLetterCode
   */
  exports.prototype['CountryThreeLetterCode'] = undefined;
  /**
   * Two-letter ISO 3166-1 country code
   * @member {String} CountryISOTwoLetterCode
   */
  exports.prototype['CountryISOTwoLetterCode'] = undefined;
  /**
   * True if this country is currently a member of the European Union (EU), false otherwise
   * @member {Boolean} IsEuropeanUnionMember
   */
  exports.prototype['IsEuropeanUnionMember'] = undefined;



  return exports;
}));


