/**
 * currencyapi
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AvailableCurrency'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AvailableCurrency'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveCurrencyApiClient) {
      root.CloudmersiveCurrencyApiClient = {};
    }
    root.CloudmersiveCurrencyApiClient.AvailableCurrencyResponse = factory(root.CloudmersiveCurrencyApiClient.ApiClient, root.CloudmersiveCurrencyApiClient.AvailableCurrency);
  }
}(this, function(ApiClient, AvailableCurrency) {
  'use strict';




  /**
   * The AvailableCurrencyResponse model module.
   * @module model/AvailableCurrencyResponse
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>AvailableCurrencyResponse</code>.
   * Result of performing an enumerate currencies operation
   * @alias module:model/AvailableCurrencyResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>AvailableCurrencyResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AvailableCurrencyResponse} obj Optional instance to populate.
   * @return {module:model/AvailableCurrencyResponse} The populated <code>AvailableCurrencyResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Currencies')) {
        obj['Currencies'] = ApiClient.convertToType(data['Currencies'], [AvailableCurrency]);
      }
    }
    return obj;
  }

  /**
   * List of available currencies from the API
   * @member {Array.<module:model/AvailableCurrency>} Currencies
   */
  exports.prototype['Currencies'] = undefined;



  return exports;
}));


