/**
 * currencyapi
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveCurrencyApiClient) {
      root.CloudmersiveCurrencyApiClient = {};
    }
    root.CloudmersiveCurrencyApiClient.ExchangeRateResult = factory(root.CloudmersiveCurrencyApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ExchangeRateResult model module.
   * @module model/ExchangeRateResult
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>ExchangeRateResult</code>.
   * Result of performing a get exchange rate operation
   * @alias module:model/ExchangeRateResult
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ExchangeRateResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExchangeRateResult} obj Optional instance to populate.
   * @return {module:model/ExchangeRateResult} The populated <code>ExchangeRateResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ExchangeRate')) {
        obj['ExchangeRate'] = ApiClient.convertToType(data['ExchangeRate'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The exchange rate from the source to the destination currency
   * @member {Number} ExchangeRate
   */
  exports.prototype['ExchangeRate'] = undefined;



  return exports;
}));


